name: PR checks
on: pull_request

env:
  SECRET_KEY: insecure_test_key

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag microcloud.is .
      - name: Run image
        run: |
          docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key microcloud.is
          sleep 1 && curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost

  lint-scss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint scss
        run: yarn lint-scss

  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install node dependencies
        run: yarn install --immutable
      - name: Install python dependencies
        run: | 
          python3 -m pip install --upgrade pip
          sudo pip3 install -r requirements.txt
      - name: Lint python
        run: yarn lint-python

  linkchecker:
    name: linkchecker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build --tag microcloud.is .
      - name: Run image
        run: |
          docker run -d -p 80:80 --env SECRET_KEY=insecure_secret_key microcloud.is
          sleep 1 && curl --head --fail --retry-delay 5 --retry 10 --retry-connrefused http://localhost
      - name: Install linkchecker
        run: sudo pip install LinkChecker
      - name: Check internal links
        run: linkchecker --ignore-url  e_sharpen --ignore-url  w_[0-9]* --ignore-url  h_[0-9]* http://localhost --ignore-url /flags.png --ignore-url /flags@2x.png

  check-inclusive-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail-on-error: true
